name: On Push to Development Branch

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Format and overwrite declaration files
      shell: pwsh
      run: |
        $lastCommit = git log -1 --oneline
        if ($lastCommit.Contains("[skip-on-push]")) { Exit }
        yarn install
        yarn format
        yarn overwrite-declaration-files
        git add .
        git commit -m "chore: Update last commit.\n\n[skip-on-push]"
        git push
